# https://taskfile.dev
version: "3"

silent: true

# vars:
#   COMPOSE_NAME: "" # The name of the compose file to use without the extension

tasks:
  up:
    requires:
      vars: ["COMPOSE_NAME"]
    desc: Start the containers defined in the given compose file
    cmd: ./docker-compose-wrapper.sh -f ./compose/{{.COMPOSE_NAME}}-stack.yml up -d

  stop:
    requires:
      vars: ["COMPOSE_NAME"]
    desc: Stop the containers defined in the given compose file
    cmd: ./docker-compose-wrapper.sh -f ./compose/{{.COMPOSE_NAME}}-stack.yml stop

  down:
    requires:
      vars: ["COMPOSE_NAME"]
    desc: Stop the containers defined in the given compose file
    cmd: ./docker-compose-wrapper.sh -f ./compose/{{.COMPOSE_NAME}}-stack.yml down

  delete:
    requires:
      vars: ["COMPOSE_NAME"]
    desc: "WARNING: Stop and delete the containers defined in the given compose file"
    cmd: ./docker-compose-wrapper.sh -f ./compose/{{.COMPOSE_NAME}}-stack.yml down -v

  debug:
    desc: Print the compose file name
    cmd: echo "Compose file name is {{.COMPOSE_NAME}}"
