name: mariadb-stack

services:
  mariadb:
    image: mariadb:11.4
    container_name: starter-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb-vol:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d
    networks:
      - mariadb-net
    ports:
      - 3306:3306
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: starter-phpmyadmin
    depends_on:
      - mariadb
    volumes:
      - ./init/mariadb/upload:/var/www/html/upload
    environment:
      - PMA_ARBITRARY=1
      - PMA_PMADB=phpmyadmin
      - UPLOAD_LIMIT=100000000
      - PMA_UPLOADDIR=/var/www/html/upload
    networks:
      - mariadb-net
    ports:
      - 8180:80

volumes:
  mariadb-vol:
    driver: local

networks:
  mariadb-net:
    name: starter-mariadb-net
    driver: bridge
